config/routes.rb
Users::Engine.routes.draw do
  root 'users#index'
  resources :users do
    collection do
      get :adminpanel
    end
    member do
      get :contacts, :disable
    end
  end

  resources :pictures
  resources :sessions, :only => [:new, :create, :destroy]
  resources :password_resets
  resources :usertypes
  resources :relationships, :only => [:create, :destroy]

  get '/signin', :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'
end

app/models/users/relationship.rb
module Users
  # == Schema Information
  #
  # Table name: relationships
  #
  #  id         :integer          not null, primary key
  #  owner_id   :integer
  #  contact_id :integer
  #  created_at :datetime         not null
  #  updated_at :datetime         not null
  #
  class Relationship < ActiveRecord::Base
    belongs_to :owner, :foreign_key => "contact_id",
               :class_name => "User"
    validates :owner_id, :presence => :true
    validates :contact_id, :presence => :true
  end
end

app/models/users/usertype.rb
module Users
  # == Tipos de Usuario Predeterminadods
  #
  # 1 = Miembro
  # 2 = Admin
  #
  # == Schema Information
  #
  # Table name: usertypes
  #
  #  id   :integer          not null, primary key
  #  name :string(255)
  #
  class Usertype < ActiveRecord::Base
    has_many :users, :foreign_key => 'userType_id'
    validates :name, :presence => true
  end
end

app/controllers/users/application_controller.rb
module Users
  class ApplicationController < ActionController::Base
    include SessionsHelper
    layout 'layouts/application'
  end
end

app/controllers/users/password_resets_controller.rb
require_dependency "users/application_controller"

module Users
  class PasswordResetsController < ApplicationController
    before_filter :authenticate
    def new
    end
    def index
      render 'new'
    end
    def create
      user = User.find_by_email(params[:search])
      if !user.nil?
        user.send_password_reset
        redirect_to root_path, :notice => 'Instrucciones enviadas. '
      else
        render 'new', :notice => 'No existe el usuario.'
      end
    end
    def edit
      @user = User.find_by_password_reset_token!(params[:id])
    end
    def update
      @user = User.find_by_password_reset_token(params[:id])
      if @user.time_requested < 2.hours.ago
        redirect_to new_password_reset_path, :alert => 'Ha expirado el lapso de tiempo.'
      elsif @user.update_attributes(user_params)
        redirect_to root_url, :notice => 'Cambio realizado'
      else
        render 'edit'
      end
    end
    private
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end
    def authenticate
      deny_access if signed_in? && !current_user.admin?
    end
  end
end

app/controllers/users/relationships_controller.rb
require_dependency "users/application_controller"

module Users
  class RelationshipsController < ApplicationController
	before_filter :authenticate
	def create
		user = User.find(params[:format])
		current_user.create_contact(user)
		redirect_to contacts_user_path(current_user)
	end
	def destroy
		Relationship.find(params[:id]).destroy
		redirect_to contacts_user_path(current_user)
	end
	private
		def authenticate
			deny_access unless signed_in? 
		end
  end
end

app/controllers/users/sessions_controller.rb
require_dependency "users/application_controller"

module Users
  class SessionsController < ApplicationController
    def new
      @title = 'Inicio de sesion'
      @desc = 'Favor de iniciar antes de ver las acciones disponibles.' #Template messages
    end
    def create
      user = User.authenticate(params[:session][:email],
                               params[:session][:password])
      if user.nil?
        flash.now[:error] = 'Datos incorrectos'
        @title = 'Inicio de sesion'
        @desc = 'Favor de iniciar antes de ver las acciones disponibles.' #Template messages

        render 'new'
      else
        sign_in user unless user.active == 0
        if user.active == 1
          redirect_back_or user
        else
          redirect_to root_path, :flash => {:notice => 'Cuenta desactivada. '}
        end
      end
    end
    def destroy
      sign_out
      redirect_to root_path
    end
    def session_params
      session_params.require(:session).permit(:email,:password)
    end
  end
end

app/controllers/users/users_controller.rb
require_dependency "users/application_controller"

module Users
  class UsersController < ApplicationController
  before_filter :authenticate, except: [:new, :create] #Remove except if only admin can register new users
  before_filter :correct_user, only: [:edit, :update, :disable]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :disable]
  before_filter :admin_user, only: [:destroy, :adminpanel]
  def index
    if current_user.admin? 
    @users = User.paginate(:page => params[:page], per_page: 15)
    @title = 'Todos los usuarios'
    else 
    redirect_to current_user
    end  
  end
  def adminpanel
   last_connected
    @title = 'Admin Panel'
    @newuser = User.new
  end
  def show
    last_connected
    @title = @user.name
  end 
  def contacts
    @title = 'Contactos'
    @user = User.find(params[:id])
    @users = @user.contacts.paginate(:page => params[:page])
    render 'show_contacts'
  end
  def new
    if Usertype.all.count == 0 
      Usertype.create(name: "Member")
      Usertype.create(name: "Admin")
    end
    @user = User.new
    @title = 'Iniciar sesión'
  end
  def create
    if current_user.nil? 
      @user = User.new(user_params)
      if @user.save
        flash[:notice] = 'Usuario registrado correctamente.'
        sign_in @user
        redirect_to @user
        Notifications.welcome(@user).deliver_now
        if User.first == @user 
          @user.userType_id = 2 
          @user.save
        end
      else
       render 'new'
      end
    elsif current_user.admin? 
      @newuser = User.new(user_params)
       if @newuser.save 
         flash[:notice] = 'User registrado correctamente. '
         redirect_to adminpanel_users_path
       else
         render "adminpanel"
       end
    end
  end 
  def edit
    @title = 'Editar usuario'
  end
  def update
    case params[:commit]
      when 'Actualizar'
        if @user.update_attributes(user_params)
          redirect_to @user, :flash =>{:success => 'User information changed.'}
          @user.update_attributes(:updatedAt => Time.now, :lastConnection => Time.now)
        else
          render 'edit'
          @title = "Edit user"
        end
      when 'Actualizar contraseña' #Checar como activar el utf-8 o cambiar a otro valor de commit
        @user.update_attributes(user_params)
        if @user.save
          redirect_to root_path, :flash => {:success => 'Contraseña actualizada'}
        else
          render 'forgot'
        end
      else
        if current_user == @user
          @user.active = '0'
          @user.deletedAt = Time.now
          @user.updatedAt = Time.now
          @user.save(validate: false)
          sign_out
          redirect_to root_path
        elsif current_user.admin?
          @user.active = '0'
          @user.deletedAt = Time.now
          @user.updatedAt = Time.now
          @user.save(validate: false)
          redirect_to adminpanel_users_path, :flash => {:success => 'Cuenta desactivada. '}
        end
    end
  end
  def destroy
    if @user.admin? 
      redirect_to root_path, :flash => {:error => "Admins can't delete themselves. "}
    else
      @user.destroy
      redirect_to users_path, :flash => {:success => 'User deleted.'}
    end
  end
  private
    def authenticate
      deny_access unless signed_in? 
    end
    def correct_user
      @user = User.find(params[:id])
      if !current_user.nil?
       redirect_to(root_path) unless current_user?(@user) || current_user.admin? 
      end
    end
    def set_user
      @user = User.find(params[:id])
    end
    def admin_user
      redirect_to(root_path) unless current_user.admin? 
      flash[:notice] = 'No tienes permiso de accesar esta pagina. ' if !current_user.admin?
    end
    def user_params
      params.require(:user).permit(:active, :lastConnection, :updatedAt, :name, :email, :password, :password_confirmation, :lastname, :userType_id, :avatar, :avatar_file_name, :avatar_content_type, :avatar_file_size, :avatar_updated_at)
    end
  end
end

app/controllers/users/usertypes_controller.rb
require_dependency "users/application_controller"

module Users
  class UsertypesController < ApplicationController
    before_action :set_usertype, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate
    def index
      @title = 'Tipos de usuarios'
      @usertypes = Usertype.all
    end
    def show
    end
    def new
      @usertype = Usertype.new
    end
    def edit
    end
    def create
      @usertype = Usertype.new(usertype_params)

      respond_to do |format|
        if @usertype.save
          format.html { redirect_to @usertype, notice: 'Tipo de usuario creado.' }
          format.json { render :show, status: :created, location: @usertype }
        else
          format.html { render :new }
          format.json { render json: @usertype.errors, status: :unprocessable_entity }
        end
      end
    end
    def update
      respond_to do |format|
        if @usertype.update(usertype_params)
          format.html { redirect_to @usertype, notice: 'Tipo de usuario actualizado.' }
          format.json { render :show, status: :ok, location: @usertype }
        else
          format.html { render :edit }
          format.json { render json: @usertype.errors, status: :unprocessable_entity }
        end
      end
    end
    def destroy
      @usertype.destroy
      respond_to do |format|
        format.html { redirect_to usertypes_url, notice: 'Tipo de usuario destruido.' }
        format.json { head :no_content }
      end
    end
    private
    def set_usertype
      @usertype = Usertype.find(params[:id])
    end
    def authenticate
      if signed_in?
        deny_access unless current_user.admin?
      else
        deny_access
      end
    end
    def usertype_params
      params.require(:usertype).permit(:name)
    end
  end
end

app/helpers/users/application_helper.rb
module Users
  module ApplicationHelper
	def title
    base_title = ""
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  	def add_picture(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to name, "#", :onclick => h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"), title: title, remote: true
  	end
  end
end

app/helpers/users/password_resets_helper.rb
module Users
  module PasswordResetsHelper
  end
end

app/helpers/users/pictures_helper.rb
module Users
  module PicturesHelper
  end
end

app/helpers/users/relationships_helper.rb
module Users
  module RelationshipsHelper
  end
end

app/helpers/users/sessions_helper.rb
module Users
  module SessionsHelper
    def sign_in(user)
      if params[:remember_me]
        cookies.permanent.signed[:remember_token] = [user.id, user.salt]
      else
        cookies.signed[:remember_token] = [user.id, user.salt]
      end
      current_user = user
      last_connected
    end
    def current_user=(user)
      @current_user = user
    end
    def current_user
      @current_user ||= user_from_remember_token
    end
    def signed_in?
      !current_user.nil?
    end
    def sign_out
      cookies.delete(:remember_token)
      current_user = nil
    end
    def current_user?(user)
      user == current_user
    end
    def last_connected
      current_user.lastConnection = Time.now
      current_user.save(validate: false)
    end
    def deny_access
      if signed_in?
        redirect_to root_path, :flash => {:error => "No tienes permiso de accesar a esta pagina. "}
      else
        store_location
        redirect_to signin_path, :notice => "Inicia sesion antes de continuar. "
      end
    end
    def store_location
      session[:return_to] = request.fullpath
    end
    def redirect_back_or(default)
      redirect_to(session[:return_to] || default)
      clear_return_to
    end
    def clear_return_to
      session[:return_to] = nil
    end
    private
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
  end
end

app/helpers/users/users_helper.rb
module Users
  module UsersHelper
  end
end

app/helpers/users/usertypes_helper.rb
module Users
  module UsertypesHelper
  end
end

app/views/users/users/_fields.html.erb
<%= f.input :avatar, as: :file, label: "Foto de Perfil"%> 
<%= f.input :name,label: "Nombre", :input_html => {:style => 'width: 200px' } %>
<%= f.input :lastname, label: "Apellido", :input_html => {:style => 'width: 200px' } %>
<%= f.input :email, :input_html => {:style => 'width: 200px'} %>
<%= f.input :password, label: "Contrasena", input_html: {style: 'width: 200px'} %>
<% if current_user.nil? || ( !current_user.nil? && !current_user.admin? ) %>
<%= f.input :password_confirmation, label: "Confirmacion de contrasena ", input_html: {style: 'width: 200px'} %>
<% end %>
<% if current_user.present? %>
	<% if current_user.admin? %> 
<%= f.input :active, label: "Estado de cuenta", input_html: {style: 'width: 200px'}, collection: [['Inactiva', '0' ], ['Activa','1']] %>
<%= f.input :userType_id, label: "Tipo de Usuario", collection: Users::Usertype.all.map{|m|[m.name, m.id]} %>
	<% end %>
<% end %>

app/views/users/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <% if @user.errors.any? %>
   <div class = "panel panel-danger">
    <div class = "panel-heading">
      <h4><%= pluralize(object.errors.count, "error impide", "errores impiden") %> 
      que sea guardado:  </h4>
    </div>
    <div class="panel-body"><%object.errors.full_messages.each do |message|%> 
    <ul><li><%=message %></li> 
    </ul>
    <% end %> 
    </div>
  </div>
  <% end %>
   <%= render 'fields', f: f %>
  <div class="actions">
    <%= f.submit "Crear" %>
  </div>
<% end %>

app/views/users/users/_picture_fields.html.erb
<%= f.file_field :url %>

app/views/users/users/_user.html.erb
<li>
	<%= link_to user.name, user %> 
	<% if current_user.admin? %>
	|
	<%= link_to "editar", edit_user_path(user) %> 
	|
	<%= link_to "destruir", user, :method => :delete %>
	<% end %> 
   <% if current_user != user %> 
		<% if current_user.contact?(user) %> 
		|
		<%= link_to "Quitar de Contactos", relationship_path(current_user.contact?(user)), method: :delete %>
		<% else %>
		|
		<%= link_to "Agregar Contacto", relationships_path(user), method: :post %>
		<% end %>
	<% else %> 
	    (tú)
	<% end %>  
</li>

app/views/users/users/adminpanel.html.erb
<%= link_to 'Tipos de Usuario', usertypes_path %> 
<br>
<br>
Nuevo Usuario
<%= simple_form_for(@newuser) do |f| %>
<%= f.input :name,label: "Nombre", :input_html => {:style => 'width: 200px' } %>
<%= f.input :lastname, label: "Apellido", :input_html => {:style => 'width: 200px' } %>
<%= f.input :email, :input_html => {:style => 'width: 200px'} %>
<%= f.input :password, label: "Contrasena", input_html: {style: 'width: 200px'} %>
<%= f.input :userType_id, label: "Tipo de Usuario", collection: Users::Usertype.all.map{|m|[m.name, m.id]} %>
  <%= f.submit "Crear" %>
<% end %>
<%= link_to 'Regresar', users_path %>

app/views/users/users/edit.html.erb
<h1>Editar usuario</h1>
<%= simple_form_for(@user) do |f| %>
	<%= render 'users/shared/error_messages', :object => f.object %>
	<%= render 'fields', :f => f %> 
	<div class ="actions">
		<%= f.submit "Actualizar", class: "btn btn-primary" %>
		<%= button_tag "Desactivar Cuenta", class: "btn btn-primary" %> 
	</div>
<% end %>

app/views/users/users/index.html.erb
<div class="container">
  <div class="row" id="admhead">
      <div class="col-xs-1"></div>
      <% if current_user.nil? %>
      <div class="col-xs-2">

       </div>
      <% else %> 
      <div class="col-xs-2"></div>
      <% end %>
      <div class="col-xs-6"><h2><%= "#{current_user.name} #{current_user.lastname}" %></h2> <br> 
        <%= current_user.email %>
      </div>
      <div class="col-xs-3"><%= link_to "Cerrar sesion", signout_path %></div>
  </div>
  <div class="row" id="usersbuttons">
      <div class="col-xs-2"></div>
      <div class="col-xs-2"><%= link_to 'Inicio', users_path %></div>
      <div class="col-xs-2"><%= link_to 'Administrar Tipo de Usuario', usertypes_path %></div>
      <div class="col-xs-2"><%= link_to 'Agregar Usuario Nuevo', new_user_path %></div>
      <div class="col-xs-4"></div>
  </div> 
  <div class="row" id="usersindex">
    <div class="col-xs-7" style=""><%= form_tag(users_path, :method => "get", id: "search-form") do %>
     <%= select_tag(:search, options_for_select(Users::Usertype.all.map{|c|[c.name, c.id]}), include_blank: "Todos") %>
   <%= submit_tag "Ver por tipo de usuario", :name => nil, :class => 'btn btn-primary' %>
<% end %>
<% if !params[:search].blank? %> 
  <% @users = Users::User.where("userType_id = #{params[:search]}").paginate(:page => params[:page], per_page: 15) %>
<% end %> 
Cantidad de Usuarios en esta lista:<%= @users.count %>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Correo Electronico</th>
      <th>Estado</th>
      <th>Tipo de Usuario</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to "#{user.name} #{user.lastname}", user %></td>
        <td><%= user.email %></td>
        <td><%= user.active == 1 ? 'Cuenta activada' : 'Cuenta desactivada' %> </td>
        <td><%= Users::Usertype.find(user.userType_id).name %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td></td>
        <td><% if current_user.admin? && user.userType_id != 2 %> <%= link_to 'Destruir', user, method: :delete, data: { confirm: 'Are you sure?' } %> <% end %></td>
      </tr>
    <% end %>
  </tbody>  
</table>
  <div class="digg_pagination">
    <%= will_paginate @users , :container => false %>
  </div>
</div>
    <div class="col-xs-2"></div>
    <div class="col-xs-3">
    <table> 
      <tr><th>Contactos </th></tr>
      <% current_user.contacts.each do |contact| %>
        <tr><td><%= "#{contact.name} #{contact.lastname}" %></td></tr>
      <% end %>
    </table>
    </div>
  </div>
</div>

app/views/users/users/new.html.erb
<% if current_user.admin? %> 
<div class="container">
  <div class="row" id="admhead">
      <div class="col-xs-1"></div>
      <div class="col-xs-2">FOTO!!!</div>
      <div class="col-xs-6"><h2><%= "#{current_user.name} #{current_user.lastname}" %></h2> <br> 
        <%= current_user.email %>
      </div>
      <div class="col-xs-3"><%= link_to "Cerrar sesion", signout_path %></div>
  </div>
  <div class="row" id="usersbuttons">
      <div class="col-xs-2"></div>
      <div class="col-xs-2"><%= link_to 'Inicio', users_path %></div>
      <div class="col-xs-2"><%= link_to 'Administrar Tipo de Usuario', usertypes_path %></div>
      <div class="col-xs-2"><%= link_to 'Agregar Usuario Nuevo', new_user_path %></div>
      <div class="col-xs-4"></div>
  </div> 
  <div class="row" id="usersindex">
    <h3>Usuario Nuevo</h3>

    <%= render 'form' %>

  </div>
</div>
<% else %> 
	<h1>Nuevo Usuario</h1>

	<%= render 'form' %>

	<%= link_to 'Atras', users_path %>
<% end %>

app/views/users/users/show.html.erb
<table class ="profile" summary= "Profile Information"> 
  <tr>
    <td class = "main">
      <h1><%= @user.name %> <%= @user.lastname %> </h1>
    </td> 
    <% if current_user.admin? %>
     <td class ="sidebar round">
     	<strong>Tipo de Usuario: </strong><%= Users::Usertype.find(@user.userType_id).name %>
     </td>
     <% end %>
  </tr>
  <% if current_user == @user %>
  <tr><td>Contactos: <br>
    <%= render 'users/shared/stats' %> 
    </td></tr>
  <% else %> 
    <% if current_user.contact?(@user) %> 
    |
    <%= link_to "Quitar de Contactos", relationship_path(current_user.contact?(@user)), method: :delete %>
    <% else %>
    |
    <%= link_to "Agregar Contacto", relationships_path(@user), method: :post %>
    <% end %>
  <% end %>
</table>

app/views/users/users/show_contacts.html.erb
<%= form_tag(contacts_user_path(@user), :method => "get", id: "search-form") do %>
  	 <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
 	 <%= submit_tag "Search", :name => nil %>
<% end %>
<% if !params[:search].blank? %> 
	<% @someusers = Users::User.search(params[:search]).paginate(:page => params[:page]) %> 
		<% if !@someusers.nil? %> 
			<%= render @someusers%>  
			<div class="digg_pagination">
			<%= will_paginate @someusers , :container => false %>
			</div>
		<% end %>
<% end %> 
<table summary="Contactos del Usuario"> 
	<tr>
		<td class="main">
			<h1><%= "Contactos" %></h1>
			<% if @users.any? %>
				<ul class="users">
					<%= render @users %> 
				</ul>
			<% else %>
					No tienes ningun contacto aun.
			<% end %> 
		</td>
		<td class ="sidebar round">
			<%= render 'users/shared/stats' %>
		</td>
	</tr>
</table>